name: Build and Deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Update .env file
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production' 
        run: sh ./scripts/update-endpoint.sh ${GITHUB_REF##*/}
          
      - name: Commit files
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production'
        run: |
          git status
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "CI: Update .env file" -a
          
      - name: Push changes
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extract_branch.outputs.branch }}
       
      - name: Deploy to Platform.sh
        uses: joelwmale/webhook-action@master
        env:
            WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
            data: "Deploy to Platform.sh!"
